[workspace]
members = [
    "lispy_core",
    "lispy"
]

[workspace.dependencies]
lispy_core = { path = "../lispy_core/" }
peg = "0.8.3"
rug = "1.24.1"
libloading = "0.8.3"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
