[package]
name = "lispy_core"
version = "0.1.0"
edition = "2021"


[lib]
name = "lispy_core"
crate-type = ["cdylib", "rlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.8.3"
rug = "1.24.1"
libloading = "0.8.3"
